### PR TITLE
Fix build errors in test code

### PR DESCRIPTION
**Pull request by neilmayhew**
Two cherry picks from dsf. However, you may prefer a merge.

---
This change is [Reviewable](https://reviewable.io/reviews/clinty/debian-haskell/1)

### CODE REVIEW

**Comment by neilmayhew** [comment]
BTW, I don't see a way to create an issue against your repository. If this is now the definitive repo for the package, you may want to fix that.

**Comment by clinty** [comment]
Sorry, I missed this and now I have no recollection of the conflicting changes involved.

**Comment by neilmayhew** [comment]
I don't remember anything after 2 years either! However, I'll take a look and see if I can figure out what this was about.

**Comment by neilmayhew** [comment]
You have since made changes in 1dfe3a05 that make these cherry-picks unnecessary. Closing.

**Comment by neilmayhew** [comment]
However, please, please enable the issue tracker!

**Pull request closed without merging**
